# Generated by Django 3.2.6 on 2021-08-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default='0123456789', max_length=30),
            preserve_default=False,
        ),
    ]
